// key-facts.js
// Genesis key facts for between-question overlay

window.KEY_FACTS = [
    `Author: Moses is traditionally considered the author of Genesis and the entire Pentateuch (Genesis–Deuteronomy). This is supported by internal evidence (e.g., Exodus 17:14 KJV: "And the LORD said unto Moses, Write this for a memorial in a book..."; Numbers 33:2 KJV: "And Moses wrote their goings out according to their journeys by the commandment of the LORD..."; Deuteronomy 31:9 KJV: "And Moses wrote this law, and delivered it unto the priests...") and external references, such as Jesus's affirmation in John 5:46-47 (KJV): "For had ye believed Moses, ye would have believed me: for he wrote of me. But if ye believe not his writings, how shall ye believe my words?" However, later editorial additions, like the account of Moses’s death in Deuteronomy 34, were likely added by inspired scribes such as Joshua or Ezra.`,
    `Date of Writing: Genesis was written around 1445 B.C., which correlates with the early date of the Exodus and aligns with the traditional chronology upheld by conservative scholars.`,
    `Original Audience: The book was written for the Israelites who had been recently delivered from Egypt. They needed to understand their origins, their identity, and the character of their covenant God, Yahweh.`,
    `Genre: Genesis is a theological-historical narrative, not a myth or a scientific text. Its opening chapters present real events through ancient Near Eastern literary forms to communicate theological truths, revealing God as the sovereign Creator and distinguishing Him from the polytheistic deities of Egypt and Mesopotamia.`,
    `Primary Purpose: The primary purpose of Genesis is theological: to establish a foundation for Israel's worldview that one eternal, personal God created and sustains everything. The book dismantles pagan cosmologies by asserting monotheism and divine intentionality.`,
    `Interpretive Context: Genesis should be interpreted within its ancient Near Eastern (ANE) context, not a modern scientific one. The author was not addressing concepts like evolution or astrophysics but was revealing divine order, covenant purpose, and moral accountability.`,
    `Biblical Meta-narrative: Genesis lays the groundwork for the entire biblical meta-narrative of creation, fall, promise, and redemption. It introduces humanity’s sin, God’s justice, and His covenant plan that culminates in the Messiah, as first promised in Genesis 3:15 (KJV): "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel."`,
    `"In the beginning": The Hebrew term bərēʾšît is most often translated as "in the beginning," emphasizing the absolute start of time, space, and matter from nothing (creatio ex nihilo).`,
    `"Created" (bara): This Hebrew verb is used exclusively for divine activity and refers to the act of creating something from nothing (creatio ex nihilo), as seen in Genesis 1:1 (KJV): "In the beginning God created the heaven and the earth."`,
    `"Made" (asah): This Hebrew verb refers to the act of fashioning or appointing something from pre-existing materials, emphasizing divine ordering.`,
    `Creation of Angels: Angels were created before "the beginning," as they witnessed the creation of the heavens and the earth, as described in Job 38:7 (KJV): "When the morning stars sang together, and all the sons of God shouted for joy?"`,
    `The Godhead (Elohim): The name for "God" in Genesis 1 is Elohim, a plural noun used with a singular verb. This grammatical structure indicates both unity and diversity within the Godhead (Father, Son, and Holy Spirit).`,
    `"The heavens and the earth": This phrase is a Hebraic figure of speech known as a merism, which means "everything" or the entire universe, including the sun, moon, stars, and all life.`,
    `Two Spheres of Revelation: The Bible (special revelation) and nature (general revelation) are two distinct spheres through which God reveals Himself, and they do not contradict one another.`,
    `Genesis 1:2 Onward: The focus of the narrative shifts after Genesis 1:1. It moves from the initial act of creation (bara) to the six-day process of ordering and preparing (asah) the environment for humanity.`,
    `The Meaning of ’eretz: The Hebrew word ’eretz can mean the entire earth, a specific region, or the ground itself, depending on the context. In Genesis 1:2 (KJV), "And the earth was without form, and void...", it most naturally refers to the whole planet in its unformed state. The passage thus portrays God preparing the entire earth to be a habitable home for humanity.`,
    `Tohu Wabohu: Translated as "formless and desolate," this phrase literally means "uninhabitable wilderness" or "waste and void." It describes an uncultivated state requiring order and preparation, not necessarily chaos or non-existence.`,
    `Darkness and the Deep: The Hebrew terms tehom ("the deep") and "darkness" describe the earth’s initial, unformed, and unilluminated condition. This state was not chaotic or evil but simply uninhabited, awaiting divine ordering and the introduction of light and life.`,
    `Day 1 – Light: The light of the first day was a newly created phenomenon that filled the world with illumination. While God Himself is Light in a spiritual sense, this act signifies His creation of physical light—distinct from Himself—as the first evidence of His creative power.`,
    `Day 2 - Expanse (Sky): God "made" (asah) the expanse to separate the "waters above" (clouds) from the "waters below" (seas). The Hebrew word raqia (expanse or firmament) refers to the sky or atmosphere.`,
    `Day 3 - Dry Land and Vegetation: God gathered the waters to allow dry land to appear and then commanded the land to "sprout vegetation," which it did instantaneously, as stated in Genesis 1:11 (KJV): "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so."`,
    `Day 4 - Lights Appointed: On the fourth day, God created and appointed the sun, moon, and stars to serve as signs for seasons, days, and years, affirming His sovereignty over nature.`,
    `Day 5 - Sea and Sky Creatures: God created life in the waters and the sky. The use of the verb bara (create) signifies a distinct creative act, indicating that God directly formed aquatic and avian life by His word.`,
    `Day 6 - Land Animals and Humans: God created land animals, each according to its kind. Humanity was the climax of His work, made in God’s image with moral capacity and dominion over creation.`,
    `Creation of Man: Man is uniquely described as being created (bara), formed (yatsar), and made (asah) by God. These terms together depict God’s intimate and purposeful creation of humanity.`,
    `The First Man: The genealogies in Genesis 5 and Luke 3 presuppose that Adam was the first man, as they trace humanity’s line directly back to him.`,
    `The Dominion Mandate: The Hebrew words kabash (subdue) and radah (rule) call for active stewardship, not harsh domination. In Genesis 1:28 (KJV), humanity was tasked to manage creation responsibly: "...and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth."`,
    `Original Diet: According to Genesis 1:29-30, humanity was originally given vegetation for food. Genesis 1:29 (KJV) states: "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat." The consumption of meat was not permitted until after the Flood, as recorded in Genesis 9:3 (KJV): "Every moving thing that liveth shall be for meat for you; even as the green herb have I given you all things."`,
    `Death: Before sin, there was no animal death, suffering, or predation. Scripture teaches that creation was "very good," as declared in Genesis 1:31 (KJV): "And God saw every thing that he had made, and, behold, it was very good." Death entered the world only after the disobedience of Adam and Eve, as explained in Romans 5:12 (KJV): "Wherefore, as by one man sin entered into the world, and death by sin; and so death passed upon all men, for that all have sinned."`
];

