// key-facts.js
// Genesis key facts for between-question overlay

window.KEY_FACTS = [
    `Author: Moses is traditionally regarded as the author of Genesis (and the entire Pentateuch: Genesis–Deuteronomy). Internal evidence (e.g., Exodus 17:14; Numbers 33:2; Deuteronomy 31:9) and external references (e.g., Jesus in John 5:46-47) affirm Mosaic authorship. However, later editorial additions (e.g., Moses’ death in Deuteronomy 34) were likely added by inspired scribes such as Joshua or Ezra.`,
    `Date of Writing (Genesis): Around 1445 B.C., correlating with the early date of the Exodus. This aligns with the traditional chronology upheld by conservative scholars.`,
    `Original Audience: The Israelites freshly delivered from Egypt, who needed to understand their origins, identity, and the character of their covenant God, Yahweh.`,
    `Genesis is a theological-historical narrative, not a myth or a scientific text. The first chapters present real events conveyed through ancient Near Eastern literary forms that communicate theological truths. They reveal God as Creator and Sovereign, distinguishing Him from the polytheism of Egypt and Mesopotamia.`,
    `The primary purpose is theological: to establish a foundation for Israel's worldview—that one eternal, personal God created and sustains everything. Genesis dismantles pagan cosmologies by asserting monotheism and divine intentionality.`,
    `The interpretive context must be ancient Near Eastern (ANE), not modern scientific. The author was not addressing evolution or astrophysics but revealing divine order, covenant purpose, and moral accountability.`,
    `Genesis lays the groundwork for the biblical meta-narrative: creation, fall, promise, and redemption. It introduces humanity’s sin, God’s justice, and His covenant plan culminating in the Messiah (Genesis 3:15). As first promised in Genesis 3:15 (KJV): "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel."`,
    `"In the beginning": bərēʾšît is most translated into English as "in the beginning," emphasizing the absolute start of time, space, and matter from nothing (creatio ex nihilo)`,
    `"Created" (bara): Used exclusively for divine activity—creation ex nihilo (out of nothing), as in Genesis 1:1. Genesis 1:1 (KJV), "In the beginning God created the heaven and the earth,"`,
    `"Made" (asah): Refers to fashioning from existing materials, emphasizing divine ordering or appointment.`,
    `Angels' Creation: Angels were created before "the beginning" as they witnessed the creation of the heavens and the earth (Job 38:7).`,
    `The Godhead (Elohim): The name "God" in Genesis 1 is Elohim in Hebrew, a plural noun used with a singular verb, indicating unity and diversity within the Godhead (Father, Son, and Holy Spirit).`,
    `"The heavens and the earth": This phrase is a Hebraic figure of speech called a merism, meaning "everything" or the entire universe, including the sun, moon, stars, and all life.`,
    `Two Spheres of Revelation: The Bible (special revelation) and nature (general revelation) are two spheres through which God reveals Himself, and they do not contradict each other.`,
    `Genesis 1:2 onward shifts focus from the initial act (bara) in 1:1 to the six-day process of ordering and preparing (asah) the environment for humanity.`,
    `The Hebrew word ’eretz can refer to the entire earth, a specific region, or the ground itself, depending on context. However, in Genesis 1:2, it most naturally refers to the whole planet in its unformed state. Thus, rather than describing a localized land such as the Promised Land, the passage portrays God preparing the entire earth to become a habitable home for humanity.`,
    `Tohu wabohu ("Formless and desolate") literally means "uninhabitable wilderness" or "waste and void," describing an uncultivated state, not necessarily chaos or non-existence. This state requires ordering and preparation, fitting the context of a land being made ready.`,
    `Darkness and the Deep: The Hebrew terms tehom (“the deep”) and “darkness” describe the earth’s initial, unformed, and unilluminated condition before God began His creative work. This state was not chaotic or evil but simply uninhabited, awaiting divine ordering and the introduction of light and life to the entire planet.`,
    `Day 1 – Light: The “light” of the first day was a new, created phenomenon that filled the freshly made world with illumination. While God Himself is Light in a spiritual and moral sense, this creative act does not mean He created His own essence. Rather, He brought into existence physical light — distinct from Himself — as the first tangible evidence of His creative power and the beginning of order in the material universe.`,
    `Day 2 - Expanse (Sky): God "made" (Asah) the expanse to separate the waters on the land from the water in the clouds (atmosphere). Hebrew word raqia (expanse or firmament) refers to the sky or atmosphere separating “waters above” (clouds) from “waters below” (seas).`,
    `Day 3 - Dry Land and Vegetation: God gathered the waters to let dry land appear. He then commanded the land itself to "sprout vegetation," which it did. The land was made visible by water collection, and that vegetation began through divine command (Genesis 1:9–13). The text supports instantaneous creation, not natural growth.`,
    `Day 4 - Lights Appointed: On the fourth day, God created and appointed the sun, moon, and stars to serve as signs for seasons, days, and years. These celestial bodies were brought into existence during creation week, not merely made visible or assigned functions. The account emphasizes God’s creative power and sovereignty over nature, affirming that He alone is the source of light and life.`,
    `Day 5 - Sea and Sky Creatures: On the fifth day, God created new life in the waters and the sky. The Hebrew verb bara (create) signifies a distinct creative act — not modification of preexisting creatures. God directly formed aquatic and avian life by His word, demonstrating His creative power and authority over all living beings.`,
    `Day 6 - Land Animals and Humans:  God created land animals and humanity. The animals were newly created on this day, each according to its kind. Humanity was the climax of creation — made in God’s image, with moral capacity and dominion over creation.`,
    `Creation of Man: Man is uniquely described as being created (bara), formed (yatsar), and made (asah) by God. Bara (divine creation), yatsar (forming as a potter), and asah (fashioning) describe God’s intimate creation of humanity.`,
    `First Man: Genealogies in Genesis presuppose that Adam was the first man. Genesis 5 and Luke 3 trace genealogy directly to Adam.`,
    `Dominion Mandate:  The Hebrew words kabash (subdue) and radah (rule) express active stewardship, not harsh domination. Humanity was called to manage creation responsibly, reflecting God’s character of love, care, and order, rather than to exercise aggressive control.`,
    `Original Diet: Humanity was given vegetation for food; eating meat is not forbidden but unmentioned until after the Flood. Genesis 1:29–30 specifies a plant-based diet. Genesis 9:3 later permits meat consumption. Humanity was originally designed for plant nourishment.`,
    `Death: There was no animal death, suffering, or predation before sin. Scripture teaches that all creation was “very good” (Genesis 1:31). Death entered the world only after Adam and Eve’s disobedience (Romans 5:12). The original creation was harmonious and peaceful, free from violence or decay.`
];

